spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://localhost:9999
    auth-service:
      path: /user/**
      url: http://localhost:8181/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      accessTokenUri: http://localhost:8181/uaa/oauth/token
      userAuthorizationUri: http://localhost:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret